//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>A vantage street for use with NYC ZR 81-27.</summary>
    [JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class DaylightEvaluationVantageStreet : Element
    {
        [JsonConstructor]
        public DaylightEvaluationVantageStreet(double @score, double @numberOfVantagePoints, double @centerlineDistance, System.Guid @id = default, string @name = null)
            : base(id, name)
        {
            this.Score = @score;
            this.NumberOfVantagePoints = @numberOfVantagePoints;
            this.CenterlineDistance = @centerlineDistance;
            }
        
        // Empty constructor
        public DaylightEvaluationVantageStreet()
            : base()
        {
        }
    
        /// <summary>Score for the street.</summary>
        [JsonProperty("Score", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Score { get; set; }
    
        /// <summary>How many vantage points were generated for this street.</summary>
        [JsonProperty("NumberOfVantagePoints", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double NumberOfVantagePoints { get; set; }
    
        /// <summary>Calculated centerline distance of street</summary>
        [JsonProperty("CenterlineDistance", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double CenterlineDistance { get; set; }
    
    
    }
}